[package]
name = "sans-io-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
mio = { version = "0.8", features = ["os-poll", "net"], optional = true }
parking_lot = "0.12"

[dev-dependencies]
env_logger = "0.11.2"

[features]
default = ["mio-backend"]
mio-backend = ["mio"]
