[package]
name = "sans-io-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
heapless = "0.8"
log = "0.4"
mio = { version = "0.8", features = ["os-poll", "net"], optional = true }
parking_lot = "0.12"

[dev-dependencies]
mockall = "0.12.1"
env_logger = "0.11"
tiny_http = "0.12"
str0m = "0.4.1"
faster-stun = "1.0.2"

[features]
default = ["mio-backend"]
mio-backend = ["mio"]
